[workspace]
name = "jaxlib-cuda-repro"
channels = ["conda-forge"]
platforms = ["linux-64"] # CUDA jaxlib wheels on conda-forge are linux-64

[system-requirements]
cuda = "12"

[feature.jax060.dependencies]
python = "3.12.*"                # avoid ambiguity warning
jax = "==0.6.0"
jaxlib = { version = "==0.6.0", build = "*cuda*" }

[feature.jax062-200.dependencies]
python = "3.12.*"                # avoid ambiguity warning
jax = "==0.6.2"
jaxlib = { version = "==0.6.2", build = "*cuda*_200" }

[feature.jax062-201.dependencies]
python = "3.12.*"                # avoid ambiguity warning
jax = "==0.6.2"
jaxlib = { version = "==0.6.2", build = "*cuda*_201" }

[feature.jax070.dependencies]
python = "3.12.*"
jax = "==0.7.0"
jaxlib = { version = "==0.7.0", build = "*cuda*" }

[feature.jax070pypi.dependencies]
python = "3.12.*"

[feature.jax070pypi.pypi-dependencies]
jax = { version = "==0.7.0", extras = ["cuda12"] }

[environments]
jax060 = ["jax060"]
jax062-200 = ["jax062-200"]
jax062-201 = ["jax062-201"]
jax070 = ["jax070"]
jax070pypi = ["jax070pypi"]

[tasks]
repro = "python -c 'import jax; print(\"Jax default backend: \" + jax.default_backend()); import jax.numpy; jax.numpy.array([1,2,3])'"
simple_repro = "python hardcoded_dlopen.py"
print_symbols_jax_common = "nm -s $CONDA_PREFIX/lib/python3.12/site-packages/jaxlib/libjax_common.so | grep coordination_agent_recoverable"
print_symbols_xla_cuda_plugin = "nm -s $CONDA_PREFIX/lib/python3.12/site-packages/jax_plugins/xla_cuda12/xla_cuda_plugin.so | grep coordination_agent_recoverable"

[tasks.print_symbols]
cmd = "true" # no-op; run only dependencies
depends-on = ["print_symbols_jax_common", "print_symbols_xla_cuda_plugin"]

