[workspace]
name = "jaxlib-cuda-repro"
channels = ["conda-forge"]
platforms = ["linux-64"] # CUDA jaxlib wheels on conda-forge are linux-64

[system-requirements]
cuda = "12"

[dependencies]
python = "3.12.*"

[feature.jax060.dependencies]
jax = "==0.6.0"
jaxlib = { version = "==0.6.0", build = "*cuda*" }

[feature.jax062-200.dependencies]
jax = "==0.6.2"
jaxlib = { version = "==0.6.2", build = "*cuda*_200" }

[feature.jax062-201.dependencies]
jax = "==0.6.2"
jaxlib = { version = "==0.6.2", build = "*cuda*_201" }

[feature.jax070.dependencies]
jax = "==0.7.0"
jaxlib = { version = "==0.7.0", build = "*cuda*" }

[feature.jax060pypi.pypi-dependencies]
jax = { version = "==0.6.0", extras = ["cuda12"] }

[feature.jax061pypi.pypi-dependencies]
jax = { version = "==0.6.1", extras = ["cuda12"] }

[feature.jax062pypi.pypi-dependencies]
jax = { version = "==0.6.2", extras = ["cuda12"] }

[feature.jax070pypi.pypi-dependencies]
jax = { version = "==0.7.0", extras = ["cuda12"] }

[environments]
# jax 0.6.0 from conda-forge 
jax060 = ["jax060"]
# jax 0.6.0 from pypi
jax060pypi = ["jax060pypi"]
# jax 0.6.1 from pypi
jax061pypi = ["jax061pypi"]
# jax 0.6.2 from pypi
jax062pypi = ["jax062pypi"]
# jax 0.6.2 build 200 from conda-forge
jax062-200 = ["jax062-200"]
# jax 0.6.2 build 201 from conda-forge
jax062-201 = ["jax062-201"]
# jax 0.7.0 from conda-forge
jax070 = ["jax070"]
# jax 0.7.0 from pypi
jax070pypi = ["jax070pypi"]

[tasks]
repro = "python -c 'import jax; print(\"Jax default backend: \" + jax.default_backend()); import jax.numpy; jax.numpy.array([1,2,3])'"
simple_repro = "python hardcoded_dlopen.py"
print_symbols_jax_common = "nm -s $CONDA_PREFIX/lib/python3.12/site-packages/jaxlib/libjax_common.so | grep coordination_agent_recoverable"
print_symbols_xla_cuda_plugin = "nm -s $CONDA_PREFIX/lib/python3.12/site-packages/jax_plugins/xla_cuda12/xla_cuda_plugin.so | grep coordination_agent_recoverable"
print_all_flags_jax_common = "nm -s $CONDA_PREFIX/lib/python3.12/site-packages/jaxlib/libjax_common.so | grep FLAGS_"
print_all_flags_xla_cuda_plugin = "nm -s $CONDA_PREFIX/lib/python3.12/site-packages/jax_plugins/xla_cuda12/xla_cuda_plugin.so | grep FLAGS_"

[tasks.print_symbols]
cmd = "true" # no-op; run only dependencies
depends-on = ["print_symbols_jax_common", "print_symbols_xla_cuda_plugin"]

[tasks.print_all_flags]
cmd = "true" # no-op; run only dependencies
depends-on = ["print_all_flags_jax_common", "print_all_flags_xla_cuda_plugin"]
